export { default as IconRight } from "./IconRight";
export { default as WalletIcon } from "./WalletIcon";
export { default as IconDots } from "./IconDots";
export { default as IconTwitter } from "./IconTwitter";
export { default as IconNFT } from "./IconNFT";
export { default as IconStar} from "./IconStar";
export { default as IconLike} from "./IconLike";
export { default as IconRightNormal} from "./IconRightNormal";
export { default as IconAvatar} from "./IconAvatar";
export { default as IconShare } from "./IconShare";
export { default as IconSave } from "./IconSave";
export { default as IconHeart } from "./IconHeart";
export { default as IconComment } from "./IconComment";
export { default as IconSwitch } from "./IconSwitch";