const API_URL = process.env.NEXT_PUBLIC_API_HOST;
const SOL_WALLET = process.env.NEXT_PUBLIC_SOL_ADDRESS;
const SOL_NETWORK = process.env.NEXT_PUBLIC_SOL_NETWORK;
const COMMING_SOON = process.env.NEXT_PUBLIC_MODE_COMMING_SOON;
const BONK_ADDRESS = process.env.NEXT_PUBLIC_BONK_ADDRESS;


export { API_URL, SOL_WALLET, SOL_NETWORK, COMMING_SOON, BONK_ADDRESS };
