export const initialHomeContextTypes = {
  users: {
    createdAt: 0,
    updatedAt: 0,
    isDeleted: true,
    userId: "",
    username: "",
    role: "",
    type: "",
    jobTitle: "",
    organization: "",
    experience: [],
    fullName: "",
    email: "",
    phoneNumber: "",
    wallets: [],
    socialProfiles: [
      {
        social: "",
        username: "",
      },
    ],
    twitterPoints: 0,
    royaltyPoints: 0,
    totalPoints: 0,
    avatar: "",
    bio: "",
    coverImage: "",
    dob: "",
    gender: "",
    location: "",
    verificationStatus: "",
    referralCode: "",
    lastLogin: "",
    twitterInfo: {
      twitterPoints: 0,
      royaltyPoints: 0,
      totalPoints: 0,
      avatar: "",
      coverImage: "",
      verificationStatus: true,
      followers: 0,
      following: 0,
      externalUrl: null,
      numberOfTweets: 0,
      creationDate: "",
    },
  },
  trendingKols: {
    createdAt: 0,
    updatedAt: 0,
    isDeleted: true,
    userId: "",
    username: "",
    fullName: "",
    twitterPoints: 0,
    royaltyPoints: 0,
    totalPoints: 0,
    avatar: "",
    coverImage: "",
    verificationStatus: true,
    followers: 0,
    following: 0,
    externalUrl: "",
    numberOfTweets: 0,
    creationDate: "",
  },
  trendingProjects: {
    id: "",
    coinId: 0,
    name: "",
    symbol: "",
    marketCapRank: 59,
    thumb: "",
    small: "",
    large: "",
    slug: "",
    priceBtc: "",
    score: 0,
  },
  feature: {
    createdAt: 0,
    updatedAt: 0,
    isDeleted: true,
    userId: "",
    username: "",
    role: "",
    type: "",
    jobTitle: "",
    organization: "",
    experience: [],
    fullName: "",
    email: "",
    phoneNumber: "",
    wallets: [],
    socialProfiles: [
      {
        social: "",
        username: "",
      },
    ],
    twitterPoints: 0,
    royaltyPoints: 0,
    totalPoints: 0,
    avatar: "",
    bio: "",
    coverImage: "",
    dob: "",
    gender: "",
    location: "",
    verificationStatus: "",
    referralCode: "",
    lastLogin: "",
    twitterInfo: {
      twitterPoints: 0,
      royaltyPoints: 0,
      totalPoints: 0,
      avatar: "",
      coverImage: "",
      verificationStatus: true,
      followers: 0,
      following: 0,
      externalUrl: null,
      numberOfTweets: 0,
      creationDate: "",
    },
  },
};
