export const dataInitalProjectDetail = {
  projectDetail: {
    name: "",
    description: "",
    image: "",
    categories: [""],
    social: {
      twitter: "",
      facebook: "",
      telegram: "",
      github: "",
    },
    twitterFollowers: 0,
    contractAddress: "",
    whitePaper: "",
    website: "",
    projectType: "",
    primaryEcosystem: "",
    price: 0,
    circulatingSupply: "",
    maxSupply: "",
    totalSupply: "",
    ath: 0,
    athDate: "",
    volume24h: 0,
    marketCap: 0,
    marketCapRank: 0,
    fdv: 0,
    tvl: 0,
    tweets: [
      {
        tweetId: "",
        creationDate: "",
        text: "",
        mediaUrl: "",
        videoUrl: "",
        user: {
          creationDate: "",
          userId: "",
          username: "",
          name: "",
          followerCount: 0,
          followingCount: 0,
          favouritesCount: 0,
          isPrivate: true,
          isVerified: true,
          isBlueVerified: true,
          location: "",
          profilePicUrl: "",
          profileBannerUrl: "",
          description: "",
          externalUrl: "",
          numberOfTweets: 0,
          bot: true,
          timestamp: 0,
          hasNftAvatar: true,
          category: { category: "" },
          defaultProfile: true,
          defaultProfileImage: true,
          listedCount: 0,
          verifiedType: "",
        },
        language: "",
        favoriteCount: 0,
        retweetCount: 0,
        replyCount: 0,
        quoteCount: 0,
        retweet: true,
        views: 0,
        timestamp: 0,
        videoViewCount: 0,
        inReplyToStatusId: 0,
        quotedStatusId: 0,
        bindingValues: [
          {
            key: "",
            value: {
              imageValue: {
                alt: "",
                height: 0,
                width: 0,
                url: "",
              },
              type: "",
            },
          },
        ],
        expandedUrl: "",
        retweetTweetId: "",
        extendedEntities: "",
        conversationId: "",
        retweetStatus: "",
        quotedStatus: "",
        bookmarkCount: 387,
        source: "",
        communityNote: "",
      },
    ],
  },
  jobsDetail: {
    createdAt: 0,
    updatedAt: 0,
    isDeleted: false,
    jobId: "",
    projectName: "",
    tags: [""],
    jobType: "",
    isPublic: true,
    jobDescription: "",
    organization: [""],
    image: "",
    creator: "",
  },
};
