import {
  IconBoot,
  IconChangelog,
  IconCreateOffer,
  IconDashboard,
  IconDocs,
  IconFeedback,
  IconHolderBenefit,
  IconHome,
  IconKOLs,
  IconMarketingServices,
  IconViewOffer,
  IconWeb3Projects,
} from "@/assets/icons";

export const DATASIDEBAR = [
  {
    id: 0,
    label: "Home page",
    color: "#fff",
    colorArrow: "#fff",
    icon: <IconHome />,
    link: "/",
    children: [],
  },
  {
    id: 1,
    label: "Discover",
    color: "#F23581",
    colorArrow: "#F23581",
    link: null,
    icon: "",
    children: [
      {
        id: 11,
        label: "KOLs",
        icon: <IconKOLs />,
        link: "/top-ranking",
        isCommingSoon: false,
        color: "#fff",
      },
      // {
      //   id: 14,
      //   label: "Top 100 Ranking",
      //   icon: <IconMarketingServices />,
      //   link: "/top-ranking",
      //   isCommingSoon: false,
      //   color: "#fff",
      // },
    ],
  },
  {
    id: 2,
    label: "Offer Board",
    color: "#F23581",
    colorArrow: "#F23581",
    link: null,
    icon: "",
    children: [
      {
        id: 21,
        label: "My Offer",
        icon: <IconCreateOffer />,
        link: "/view-offer",
        isCommingSoon: false,
        color: "#fff",
      },
      {
        id: 22,
        label: "Marketing Services",
        icon: <IconViewOffer />,
        link: "/marketing-services",
        isCommingSoon: false,
        color: "#fff",
      },
    ],
  },
  {
    id: 3,
    label: "Comming soon",
    color: "#FDDDEA",
    colorArrow: "#FDDDEA",
    link: null,
    icon: "",
    children: [
      {
        id: 31,
        label: "Dashboard",
        icon: <IconDashboard />,
        link: "",
        isCommingSoon: true,
        color: "#637592",
      },
      {
        id: 32,
        label: "Boot",
        icon: <IconBoot />,
        link: "",
        isCommingSoon: true,
        color: "#637592",
      },
      {
        id: 33,
        label: "Holder Benefit",
        icon: <IconHolderBenefit />,
        link: "",
        isCommingSoon: true,
        color: "#637592",
      },
    ],
  },
];
export const DATASIDEBARBOTTOM = [
  { id: 1, label: "Docs", icon: <IconDocs />, isCommingSoon: true },
  { id: 2, label: "Changelog", icon: <IconChangelog />, isCommingSoon: true },
  { id: 3, label: "Feedback", icon: <IconFeedback />, isCommingSoon: true },
];
