name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_KEY }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET }}
      - name: Deploy Next.js app
        run: npx serverless
